# Generated by Django 4.2.6 on 2023-10-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egareye', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCityPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCityProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('process_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
